version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
        - unique
        - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
        - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
        - unique
        - not_null
  
  - name: stg_order_products
    columns:
    - name: order_id
      tests:
      - not_null
    - name: product_id
      tests:
      - not_null