version: 2

models:
  - name: fct_order_details
    tests:
        - dbt_utils.equal_rowcount:
            compare_model: ref('all_order_products')
  
  - name: dim_products

  - name: dim_orders

  - name: dim_customers